# Generated by Django 3.2.13 on 2022-11-11 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyboard',
            name='article_like',
        ),
        migrations.RemoveField(
            model_name='keyboard',
            name='mark',
        ),
        migrations.RemoveField(
            model_name='keyboard',
            name='user',
        ),
    ]
