# Generated by Django 3.2.13 on 2022-11-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyboard',
            name='content',
        ),
        migrations.RemoveField(
            model_name='keyboard',
            name='sound',
        ),
        migrations.RemoveField(
            model_name='keyboard',
            name='title',
        ),
        migrations.AddField(
            model_name='keyboard',
            name='key_switch',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='array',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='brand',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='connect',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='press',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='switch',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='weight',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
