# Generated by Django 3.2.13 on 2022-11-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyboard',
            name='bluetooth',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
