# Generated by Django 3.2.13 on 2022-11-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visit_date',
            field=models.CharField(max_length=30),
        ),
    ]
