# Generated by Django 3.2.13 on 2022-11-11 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trades',
            name='keyboard',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articles.keyboard'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trades',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
