# Generated by Django 3.2.13 on 2022-11-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trades',
            name='img',
            field=models.ImageField(blank=True, upload_to='img/'),
        ),
    ]
