# Generated by Django 3.2.13 on 2022-11-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trades',
            name='img',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
