# Generated by Django 3.2.13 on 2022-11-16 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
