# Generated by Django 3.2.13 on 2022-11-14 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20221114_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='Trades',
            new_name='trade',
        ),
    ]
