# Generated by Django 3.2.13 on 2022-11-10 07:45

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='connect',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, '유'), (2, '무')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='array',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'ten'), (2, 'tenkeyless')], max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='press',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, '38'), (2, '45')], max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='sound',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, '소음'), (2, '저소음')], max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, '가벼움'), (2, '중간')], max_length=3),
        ),
    ]
