# Generated by Django 3.2.13 on 2022-11-09 15:06

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followings',
        ),
        migrations.AddField(
            model_name='user',
            name='array',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='press',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='sound',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1, max_length=7),
            preserve_default=False,
        ),
    ]
