# Generated by Django 3.2.13 on 2022-11-13 16:16

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20221114_0015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='google_id',
            new_name='goo_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='array',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'ten'), (2, 'tenkeyless'), (3, '상관없음')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='connect',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, '유'), (2, '무'), (3, '상관없음')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='press',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, '가벼움'), (2, '무거움'), (3, '상관없음')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sound',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, '소음'), (2, '저소음'), (3, '상관없음')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, '가벼움'), (2, '상관없음')], max_length=3, null=True),
        ),
    ]
