# Generated by Django 3.2.13 on 2022-11-16 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_delete_message'),
        ('accounts', '0004_user_notice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_message',
        ),
        migrations.AlterField(
            model_name='message',
            name='trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reception', to='trade.trades'),
        ),
    ]
