# Generated by Django 3.2.13 on 2022-11-14 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_keyboard_bluetooth'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='keyboard',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articles.keyboard'),
            preserve_default=False,
        ),
    ]
