# Generated by Django 3.2.13 on 2022-11-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_review_like_review_like_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='hits',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
    ]
