# Generated by Django 3.2.13 on 2022-11-10 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20221110_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='article',
        ),
    ]
