# Generated by Django 3.2.13 on 2022-11-10 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_remove_reviews_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='article',
        ),
    ]
