# Generated by Django 3.2.13 on 2022-11-12 08:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0003_review_hits'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='bookmark_users',
            field=models.ManyToManyField(related_name='bookmark_reivew', to=settings.AUTH_USER_MODEL),
        ),
    ]
